name = "PoGo Default"
license = "Creative Commons Attribution 4.0 International"
license_url = "https://creativecommons.org/licenses/by/4.0/"
desc = "a default theme of PoGo"
url = "https://github.com/feisuweb/pogo"
tags = ["simple","light","default"]
min_version = "0.10.0"

[[author]]
    name = "feisuweb"
    url = "http://feisuweb.com"
    repo = "https://github.com/feisuweb"
